version: "3.8"

services:
  monitor_gdrive:
    container_name: monitor_gdrive
    build:
      context: .
    image: monitor_gdrive:latest
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json  # Monta o arquivo de credenciais dentro do contêiner
    working_dir: /app
    command: python mcp_monitor_send_hash.py
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true
