version: "3.8"

services:
  ocr_extrator:
    container_name: ocr_extrator_n8n
    image: ocr_extrator_n8n:latest
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
